version: "3.9"

services:
  dns-server:
    build:
      context: ./dns-server/
    networks:
      default:
        ipv4_address: 172.20.0.2
    volumes:
      - ./dns-server/etc/bind/named.conf:/etc/bind/named.conf
      - ./dns-server/etc/bind/named.conf.local:/etc/bind/named.conf.local
      - ./dns-server/etc/bind/named.conf.options:/etc/bind/named.conf.options
      - ./dns-server/var/lib/bind/zones/db.postgres.com:/var/lib/bind/zones/db.postgres.com
      - ./dns-server/var/nsupdate/01-failover:/var/nsupdate/01-failover
  db-master:
    image: postgres
    networks:
      default:
        ipv4_address: 172.20.0.3 
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  db-replica:
    image: postgres 
    networks:
      default:
        ipv4_address: 172.20.0.4
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  application:
    build:
      context: ./application
    networks:
      default:
        ipv4_address: 172.20.0.100
    ports:
      - "8080:8080"
    dns:
      - 172.20.0.2
    environment:
      - "DB_HOST=master.postgres.com"
      - "DB_PORT=5432"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"

