version: "3.9"

services:
  dns-server:
    build:
      context: ./dns-server/
    networks:
      default:
        ipv4_address: 172.20.0.2
    volumes:
      - ./dns-server/etc/bind/named.conf.local:/etc/bind/named.conf.local
      - ./dns-server/etc/bind/named.conf.options:/etc/bind/named.conf.options
      - ./dns-server/etc/bind/zones/db.postgres.com:/etc/bind/zones/db.postgres.com
  db-master:
    image: postgres
    networks:
      default:
        ipv4_address: 172.20.0.3 
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  db-replica:
    image: postgres 
    networks:
      default:
        ipv4_address: 172.20.0.4
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"

